version: "3.9"

services:
  backend:
    build:
      context: ./MANYTOMANY
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./front
    ports:
      - "5173:80"
    depends_on:
      - backend
